@HOST = https://xxx
@LOCALHOST = http://localhost:3000
@TOKEN = "xxx"

#### Post Mailer

POST {{HOST}}/mailer
Content-Type: application/json

{
  "token": {{TOKEN}},
  "name": "example",
  "address": "xxx",
  "message": "Example"
}

#### Get Hello
GET {{HOST}}/hello
Content-Type: application/json
