@HOST = https://kakeshin-api.vercel.app
@LOCALHOST = http://localhost:3000
@TOKEN = "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Iktha2VzaGluIiwiaWF0IjoxNTE2MjM5MDIyfQ"

#### Post Mailer

POST {{LOCALHOST}}/mailer
Content-Type: application/json

{
  "token": {{TOKEN}},
  "name": "小野",
  "address": "kakeshin.kasitaro@gmail.com",
  "message": "Axe Axe Axe Axe"
}

#### Get Hello
GET {{HOST}}/hello
Content-Type: application/json
